// ACTION TYPES
const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
const OPEN_CART = 'OPEN_CART';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
const CHANGE_CATEGORY_SELECTED = 'CHANGE_CATEGORY_SELECTED';

export {
  LOAD_PRODUCTS,
  OPEN_CART,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  INCREASE_QUANTITY,
  DECREASE_QUANTITY,
  CHANGE_CATEGORY_SELECTED,
};
